[project]
name = "cs4248-ez-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.1.1",
    "faiss-cpu>=1.12.0",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
    "sentence-transformers>=5.2.3",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
